management:
    endpoints: 
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
info:
    application:
        name: socialFolio-API
        description: API for SocialFolio media.
        author: Victor Henri
        version: '@socialFolio-API.version@1.0.0'
spring:
    profiles:
        active: ${spring_profile}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB