spring:
    datasource:
        url: #configure
        username: #configure
        password: #configure
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect # make sure the version is 8
